### ISSUE TITLE
The table of the insert panel shows unimportant information

### ISSUE THREAD

**Issue by OmnomnomTee** [Cimex97/schalplatten_dbs#11]
Nachdem ein track hinzugefügt wurde, wird dieser unten in dem table dargestellt. 
Gegenwärtig ist die query jedoch noch falsch und es werden alle tracks des Künsters dargestellt.

**Comment by Cimex97** [comment]
soll das nicht so sein, dass dann erstmal alle angezeigt werden?

**Comment by OmnomnomTee** [comment]
Keine Ahnung, ich dachte es sei so gemeint dass nur der neuste angezeigt wird. Sag mir einfach was angezeigt werden soll und ich passe es dementsprechend an.

**Comment by Cimex97** [comment]
die tabelle in Liste, sollte die nicht immer alle einträge anzeigen?

**Comment by OmnomnomTee** [comment]
Die soll alle Einträge anzeigen ja. Wenn das gegenwärtig nicht der Fall ist muss ich das ändern. In dem Issue hier bezog ich mich jedoch auf die Tabelle die bei "Eingabe" dargestellt wird.

**Comment by Cimex97** [comment]
das ist ein und das selbe table object, dann sollten wir 2 dafür anlegen, oder jedes mal die tabelle der datenbank selektieren

**Comment by OmnomnomTee** [comment]
Stimmt, dann müssen wir defintiv zwei Objekte anlegen! Ich mache mir mal Gedanken um die query für die Selektion.

**Comment by OmnomnomTee** [comment]
Es sind nun drei verschiedene Objekte. Eines für das Insert-, Search- und List-Menu
