### ISSUE TITLE
When I want to search for a track neither "Interpret" or "Song" are preselected

### ISSUE THREAD

**Issue by OmnomnomTee** [Cimex97/schalplatten_dbs#12]
Wenn man in dem Suchmenu ist hat man oben ja die Auswahl ob man nach Interpret oder Songnamen sucht. Standardmäßig ist nichts davon ausgewählt. Dies ist zum einen für den Benutzer ein potenziel unnötiger Klick und für den Controller eine unnötige abfrage, da es quasi keinen Zustand "nichts ausgewählt" geben sollte.

**Comment by Cimex97** [comment]
schon behoben.

**Comment by OmnomnomTee** [comment]
Perfekt!
