### ISSUE TITLE
Flavor text in the InsertMenu is not neccessary

### ISSUE THREAD

**Issue by OmnomnomTee** [Cimex97/schalplatten_dbs#13]
Die Felder in denen der Benutzer seine Daten eingibt haben von Anfang an einen Wert.
Titel: *Titel*
Interpret: *Interpret*
Archiv: *Archiv*
Diese Felder muss der Benutzer bei jedem Programmstart erstmal leeren, bevor er seine Daten eingeben kann. Es wäre vermutlich angenehemer wenn die Felder einfach leer wären.

**Comment by Cimex97** [comment]
ich suche nach ner Möglichkeit, wenn die angewählt werden, denn ganzen text zu makieren.

**Comment by Cimex97** [comment]
ich habe eine neue klasse geschrieben die von JTextField erbt. die einen focuslistener enthält, wenn jetzt ein jtext angewählt wird ist alles makiert.
