### ISSUE TITLE
The two buttons "Sortieren" and "Löschen" currently have no function

### ISSUE THREAD

**Issue by OmnomnomTee** [Cimex97/schalplatten_dbs#17]
Die zwei Buttons können gegenwärtig noch nicht verwendet werden.

Fortschritt
- [x] Sortieren
- [x] Löschen

**Comment by Cimex97** [comment]
wieso können die nicht benutzt werden?

**Comment by OmnomnomTee** [comment]
Weil ich es noch nicht implementiert habe. Ist eine Erinnerung an mich.

**Comment by Cimex97** [comment]
der löschen button gibt jetzt die selektierten zeilen zurück, diese müssen jetzt nur noch irgendwie aus der datenbank gelöscht werden

**Comment by Cimex97** [comment]
habe jetzt noch eine methode gemacht, die dann die archiv nummer der selektierten zeile zurück gibt

**Comment by OmnomnomTee** [comment]
Wo finde ich die Methode denn? Wenn ich im Controller bin finde ich keine Möglichkeit die Archivnummer zu bekommen.

**Comment by OmnomnomTee** [comment]
Löschen und Sortieren wurden im Controller eingepflegt und funktionieren nun.
