### ISSUE TITLE
The database connection gets closed improperly

### ISSUE THREAD

**Issue by OmnomnomTee** [Cimex97/schalplatten_dbs#19]
Wenn die Application gegenwärtig geschlossen wird, wird die Datanbank Verbindung nicht korrekt geschlossen. Dies muss dadurch gelöst werden, dass wenn die DefaultCloseOperation ausgelöst wird, die Verbindung vernümpftig geschlossen wird.

**Comment by Cimex97** [comment]
hast du den befehl zum beenden der Verbindungen bis zum controller gezogen?

**Comment by Cimex97** [comment]
musst den branch feature/create_controller pulln. Habe einen WindowListener hinzugefügt. Bevor "System.exit(0)" ausgeführt wird kannst du die datenbank anbindung schließen.

**Comment by OmnomnomTee** [comment]
Habe die Methode für das Schließen der DB Connection in den Controller eingepflegt. Das Problem ist jedoch, dass der Listener den du implementiert hast nicht ausgeführt wird. Das Fenster wird zwar geschlossen, aber den Thread läuft immer noch und es kommt nie zum Aufruf der DB.close Methode.

**Comment by OmnomnomTee** [comment]
Ein erneutes hinzufügen von JFrame.EXIT_ON_CLOSE oder JFrame.DISPOSE_ON_CLOSE hat das Problem gelöst.
