### ISSUE TITLE
No warning when the user wants to insert a duplicate track 

### ISSUE THREAD

**Issue by OmnomnomTee** [Cimex97/schalplatten_dbs#22]
Gegenwärtig gibt es noch keine Warnung/ Pop up Fenster, dass den Benutzer darüber informiert das bereits ein Song mit der selben Archivnummer in der Datanbank vorhanden ist.

**Comment by Cimex97** [comment]
ich dachte man kann einfach ein popup erzeugen im controller, beschäftige ich mich heute abend mal mit

**Comment by OmnomnomTee** [comment]
Hat sich schon erledigt, war ne Sache von 0.5 Minuten. Alle notwenidgen Methoden dafür waren bereits vorhanden ;D

**Comment by Cimex97** [comment]
nice alles klar 🥇 ;-)
